spring.application.name=ShortLink
server.port=8080

# ==========================
# = JPA CONFIGURATION
# ==========================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ============================
# = POSTGRESQL CONFIGURATION
# ============================
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASS}

# ============================
# = REDIS CONFIGURATION
# ============================
spring.data.redis.url=${REDIS_RUL}

jwt.secret=${JWT_SECRET_KEY}